<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="48Z0TT3" failures="0" tests="12" name="login.LoginTests" time="66.618" errors="1" timestamp="16 Apr 2024 13:43:40 GMT">
  <testcase classname="login.LoginTests" name="test04ExpectedWarningMessageWhenLoginCustomerWithInvalidUsername" time="5.887"/>
  <testcase classname="login.LoginTests" name="test11JustTestingJenkinsAgainPart2ERESAYESYES" time="5.571"/>
  <testcase classname="login.LoginTests" name="test12JustTestingJenkinsAgainPart2ERESAYESYES" time="4.374"/>
  <testcase classname="login.LoginTests" name="test10JustTestingJenkinsAgainPart2" time="4.448"/>
  <testcase classname="login.LoginTests" name="test01LoginCustomerSuccessfully" time="6.052"/>
  <testcase classname="login.LoginTests" name="test06ExpectedWarningMessageWhenLoginCustomerWithEmptyPassword" time="6.838"/>
  <testcase classname="login.LoginTests" name="test08AllLoginComponentsAreVisible" time="5.525"/>
  <testcase classname="login.LoginTests" name="test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes" time="5.516">
    <error message="Error in the expected message for wrong login expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error in the expected message for wrong login expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at login.LoginTests.test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes(LoginTests.java:121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </error>
  </testcase> <!-- test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes -->
  <testcase classname="login.LoginTests" name="test02ExpectedLoginPageWhenBrowserBackButtonAfterLogout" time="7.273"/>
  <testcase classname="login.LoginTests" name="test05ExpectedWarningMessageWhenLoginCustomerWithEmptyUsername" time="5.834"/>
  <testcase classname="login.LoginTests" name="test09JustTestingJenkins" time="4.421"/>
  <testcase classname="login.LoginTests" name="test03ExpectedWarningMessageWhenLoginCustomerWithInvalidPassword" time="4.879"/>
</testsuite> <!-- login.LoginTests -->
